#pragma once
#include <Windows.h>
#include <filesystem>
#include <array>
#include <iostream>
#include <xaudio2.h>
#include "Globals.h"
#include "Core/CoreTypes.h"
#include "Core/Utility/FunctionLibrary/StringLibrary.h"
#include "Core/Logging/LoggerMacros.h"
#include "Core/Logging/LogCategories.h"
#include "Core/Ini/IniFile.h"
#include "Core/Ini/IniFileManager.h"
#include "Core/Ini/IniReader.h"
#include "Core/Ini/IniWriter.h"
#include "Core//Audio/AudioEngine.h"
#include "Core//Audio/AudioMaster.h"
#include "Core//Audio/WAVLoader.h"
#include "Core/Asset/AssetLoaderRegistry.h"
#include "Core/Asset/AssetRegistry.h"
#include "Core/Asset/AssetLoader.h"
#include "Core/Asset/Asset.h"
#include "Core/Inputs/InputSystem.h"
#include "Core/SolitaireEngine.h"