#pragma once
#include <Windows.h>
#include <filesystem>
#include <array>
#include <iostream>
#include <xaudio2.h>
#include <cassert>
#include "Globals.h"
#include "Core/CoreTypes.h"
#include "Core/Utility/FunctionLibrary/StringLibrary.h"
#include "Core/Utility/Colors.h"
#include "Logging/LoggerMacros.h"
#include "Logging/LogCategories.h"
#include "Core/SolitaireEngine.h"
#include "Framework/ConsolePrompt.h"